spring:
  application:
    name: com.carsonlius-haoke-manage-dubbo-server-house-resources
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://vagrant:3307/haoke?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://vagrant:27017/testdb
# 服务的扫描包
dubbo:
  scan:
    base-packages: com.carsonlius.dubbo.server.api
    # 应用名称
  application:
    name:  dubbo-provider-house-resources
  # 协议以及端口
  protocol:
    name: dubbo
    port: 20880
  # 注册中心
  registry:
    address: zookeeper://vagrant:2181
    client: zkclient
logging:
  level:
    com.carsonlius.dubbo.server.mapper : DEBUG
